### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by ghost** [nneves/Raspberrypi_GPIO#1]
I am also building my own CNC and wishing to try out your code with a Raspberry

Can you link in the readme to more info about getting the GPIO working. Stuff like circuit board and wiring diagram from Raspberry to your 3d printer or CNC etc.

I am a bit new to this. Am more of a software guy than a hardware guy.

**Comment by nneves** [comment]
Hi Gerard,

this Raspberry_GPIO project is a prototype that I've prepared to show on a node.js event (lxjs.org) that I participated a few days ago, and it is still missing some parts, electronic wiring diagram is still required and I will update this as soon as possible (I was already supposed to, but got other things to prepare for that event).

Just to clear things, the RaspberryPi_GPIO project is only supposed to connect/disconnect remote appliances (ON/OFF) via RaspberryPi GPIO output pins, the electronic board is composed with 1 chip and 7 relays (electromagnetic switch), which will act as a digital switch for the appliance (I will make an update to the project README.md file with some illustrations).

My other project, R2C2_WebInterface is also a prototype for my CNC project that I'm also developing, but from what I've been told it may also work well with 3D printers/RepRap. It's still a young project but I'm considering to give more attention and evolve the initial idea.
NOTE: This project requires that you can connect the RaspberryPi to the CNC via serial port and send GCODE commands to your CNC, the rPi will not drive the Step Motors electronics (it could, but I'm using a more generic approach so that it can be connected to CNCs and 3d printers that are available in the market)

Looking forward to see your CNC project and really hope that you are able to use my R2C2_WebInterface to extend it's capabilities.

**Comment by nneves** [comment]
Preliminar electronic schematics (prototype board) completed: https://github.com/nneves/Raspberrypi_GPIO#electronic-schematics
